-- ============================================
-- Project 3: SQL Data Analysis
-- Student: Steve
-- Database: SalesInsightsDB
-- Table: dbo.Orders
-- ============================================

-- Query 1: Display all records
SELECT *
FROM dbo.Orders;

-- ============================================

-- Query 2: Display Product, Quantity and TotalPrice
SELECT Product, Quantity, TotalPrice
FROM dbo.Orders;

-- ============================================

-- Query 3: Display all unique products
SELECT DISTINCT Product
FROM dbo.Orders;

-- ============================================

-- Query 4: Display all orders costing more than 500
SELECT *
FROM dbo.Orders
WHERE TotalPrice > 500;

-- ============================================

-- Query 5: Display all orders sorted by highest TotalPrice
SELECT *
FROM dbo.Orders
ORDER BY TotalPrice DESC;

-- ============================================

-- Query 6: Display all orders sorted by lowest TotalPrice
SELECT *
FROM dbo.Orders
ORDER BY TotalPrice ASC;

-- ============================================

-- Query 7: Count the total number of orders
SELECT COUNT(*) AS TotalOrders
FROM dbo.Orders;

-- ============================================

-- Query 8: Count the number of different products
SELECT COUNT(DISTINCT Product) AS TotalProducts
FROM dbo.Orders;

-- ============================================

-- Query 9: Calculate total revenue
SELECT SUM(TotalPrice) AS TotalRevenue
FROM dbo.Orders;

-- ============================================

-- Query 10: Calculate total quantity sold
SELECT SUM(Quantity) AS TotalQuantitySold
FROM dbo.Orders;

-- ============================================

-- Query 11: Calculate the average order value
SELECT AVG(TotalPrice) AS AverageOrderValue
FROM dbo.Orders;

-- ============================================

-- Query 12: Calculate the average quantity ordered
SELECT AVG(Quantity) AS AverageQuantity
FROM dbo.Orders;

-- ============================================

-- Query 13: Show revenue generated by each product
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM dbo.Orders
GROUP BY Product
ORDER BY Revenue DESC;

-- ============================================

-- Query 14: Show quantity sold for each product
SELECT Product,
       SUM(Quantity) AS QuantitySold
FROM dbo.Orders
GROUP BY Product
ORDER BY QuantitySold DESC;

-- ============================================

-- Query 15: Show average sales for each product
SELECT Product,
       AVG(TotalPrice) AS AverageSale
FROM dbo.Orders
GROUP BY Product
ORDER BY AverageSale DESC;

-- ============================================

-- Query 16: Count orders by payment method
SELECT PaymentMethod,
       COUNT(*) AS TotalOrders
FROM dbo.Orders
GROUP BY PaymentMethod
ORDER BY TotalOrders DESC;

-- ============================================

-- Query 17: Count orders by order status
SELECT OrderStatus,
       COUNT(*) AS TotalOrders
FROM dbo.Orders
GROUP BY OrderStatus
ORDER BY TotalOrders DESC;